mongo:
  uri: "mongodb://localhost:27017"
  pool_size: 5
redis:
  addrs:
    - "127.0.0.1:6379"
  mode: 2 # 2 for single mode
  mastername: ""
  password: ""
backend:
  agent_heartbeat_offline_sec: 300
  user_session_lifetime_min: 1200
  auth: true